# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  FB_ID: "1008285839291918"
  FB_SECRET: "0cf728c163932c6e017f6bec8b03f388"

CLOUDINARY_URL: "cloudinary://492665496851842:jvaQlG7g9rk5w_tRrPD-YDSo-qo@daxpheqp1"

production:
  FB_ID: "1213637228655141"
  FB_SECRET: "a44af67c139ec705477e867c7ebd7293"
  HOST: 'sheltered-sands-48643.herokuapp.com'
  POSTMARK_API_TOKEN: '01a3860e-0799-43a5-9d12-1d03a6f418aa'
